version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=appdb
      - DB_USER=appuser
      - DB_PASSWORD=appuser123
    depends_on:
      - redis
      - mariadb
    networks:
      - app-network

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: admin123
      MARIADB_DATABASE: appdb
      MARIADB_USER: appuser
      MARIADB_PASSWORD: appuser123
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
