spring:
  # General Spring Boot Settings
  application:
    name: todo-app
  
  # Server Settings (default is 8080)
  server:
    port: 8080

  # Database Settings (MariaDB)
  datasource:
    url: jdbc:mariadb://mariadb:3306/appdb  # MariaDB connection URL
    username: appuser                     # MariaDB username
    password: appuser123                  # MariaDB password
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10

  # JPA/Hibernate Settings
  jpa:
    hibernate:
      ddl-auto: update                    # Options: none, update, validate, create, create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true

  # Redis Settings (if you are using Redis for caching or session storage)
  redis:
    host: redis             # Redis container hostname
    port: 6379              # Default Redis port
    password:               # If needed, set a password
    timeout: 2000           # Timeout in milliseconds
  
  # Logging Configuration
  logging:
    level:
      org.springframework: INFO
      com.example.todo: DEBUG    # Set the logging level for your project